name: "format filename"
description: "format nama file sesuai dengan peraturan kontribusi pada bellshade"
author: "bellshade"
inputs:
  filetypes:
    description: filter filename bedasarkan tipe file
    required: true
  working-directory:
    description: direktori formatter
    required: false
    default: .
  ignore-files:
    description: files/folder yang akan di ignore
    required: false
runs:
  using: composite
  steps:
    - run: echo "${{ github.action_path }}" >> GITHUB_PATH
      shell: bash
    - name: git config
      shell: bash
      run: |
        git config --global user.name github-actions[bot]
        git config --global user.email 'github-actions@user.noreply.github.com'
    - name: jalankan file formatter
      shell: bash
      run: |
        filename_formatter.sh ${{ inputs.working-directory }} ${{ inputs.filetypes }} ${{ inputs.ignore-files }}
    - name: commit perubahan
      shell: bash
      run: |
        git add ${{ inputs.working-directory }} || true
        git commit -m "chore: formatting filename" || true
        git push origin HEAD:$GITHUB_REF || true
