name: test tanpa perintah argument dari direktori
on:
  push:
    branches:
      - 'main'

jobs:
  formatter:
    runs-on: ubuntu-latest
    name: verifikasi file fromatter berjalan
    steps:
      - uses: actions/checkout@v3
      - uses: ./formatter
        with:
          filetypes: .cpp, .hpp
          working-directory: ./test_file
